#### 1. Create a 3x5 numpy array filled with random numbers from 1 to 10.

#### 1. Ստեղծեք 1-ից 10 պատահական թվերով լցված (3, 5) չափերով numpy array։

In [2]:
import numpy as np

In [4]:
a = np.random.rand(3, 5)
a.min(), a.max()

(0.03763973136415821, 0.9468972903949581)

#### 2. Create a numpy array of size 10 filled with 0s and replace its 5th value with a 3.

#### 2. Ստեղծեք 10 չափի 0-ներով լցված numpy array ու փոխարինեք դրա 5-րդ արժեքը 3 թվով։

In [5]:
a = np.zeros(10)
a[4]= 3
a

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0.])

#### 3. Create a numpy array filled with numbers from 3 to 15 i.e. ([3, 4 … 13, 14])

#### 3. Ստեղծեք 3-ից 15 թվերից բաղկացած numpy array ([3, 4 … 13, 14])

In [6]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 4. Reshape a numpy array of size 6x0 [1, 3, 5, 2, 4, 5] into an array of size 3x2 and then 2x3 without changing the original numpy array.  

#### 4. Վերածեք 6x0 [1, 3, 5, 2, 4, 5] numpy array-ը սկզբում 3x2 այնուհետև 2x3 numpy array-ների առանց սկզբնական numpy array-ը փոփոխելու։

In [9]:
b = np.array([1, 3, 5, 2, 4, 5])
b.reshape(3, -1)
b.reshape(2, -1)

array([[1, 3, 5],
       [2, 4, 5]])

#### 5. Write a function which gets a numpy array as an input and divides all of the array values by 2 over and over again, until the mean of the array numbers is <=5. Then, once the mean of the array numbers is <=5, the funtion returns the modified numpy array. 

#### 5. Գրեք ֆունկցիա, որը ստանում է numpy array ու բաժանում է դրա բոլոր արժեքները 2-ի այնքան ժամանակ մինչև որ դրանց միջին արժեքը լինի <=5։ Այնուհետև, հենց միջին արժեքը դառնում է <=5, ֆունկցիան վերադարձնում է փոփոխված numpy array-ը։

In [5]:
def mean_array(a):
    while np.mean(a) >5:
        a = a / 2
    return a

b = np.array([1, 3, 5, 2, 4, 1000])
mean_array(b)

array([ 0.015625,  0.046875,  0.078125,  0.03125 ,  0.0625  , 15.625   ])

#### 6. Write a function which gets a 5x4 numpy array filled with random numbers from 1 to 10 as an input and returns 4 different numpy arrays which are the columns of the original numpy array. Write another similar function which returns 5 different numpy arrays which are rows of the original numpy array. 

#### 6. Գրեք ֆունկցիա, որը ստանում է 1-ից 10 պատահական թվերով լցված 5x4 numpy array ու վերադարձնում է 4 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի սյուներն են։ Գրեք նմանատիպ ֆունկցիա, որը վերադարձնում է 5 տարբեր numpy array-ներ, որոնք սկզբնական numpy array-ի տողերն են։

In [6]:
def func_rows(a):
    return [np.array(i) for i in a]
def func_cols(a):
    return [np.array(i) for i in np.transpose(a)]
mat = np.random.rand(5, 4)
print(mat)
print(func_rows(mat))
func_cols(mat)

[[0.93587699 0.29983692 0.1332861  0.68802803]
 [0.44966759 0.07653596 0.1153025  0.41038376]
 [0.06598628 0.46473263 0.19554324 0.15602168]
 [0.76568718 0.64844119 0.47714135 0.99027427]
 [0.18648151 0.25646562 0.71588457 0.94498102]]
[array([0.93587699, 0.29983692, 0.1332861 , 0.68802803]), array([0.44966759, 0.07653596, 0.1153025 , 0.41038376]), array([0.06598628, 0.46473263, 0.19554324, 0.15602168]), array([0.76568718, 0.64844119, 0.47714135, 0.99027427]), array([0.18648151, 0.25646562, 0.71588457, 0.94498102])]


[array([0.93587699, 0.44966759, 0.06598628, 0.76568718, 0.18648151]),
 array([0.29983692, 0.07653596, 0.46473263, 0.64844119, 0.25646562]),
 array([0.1332861 , 0.1153025 , 0.19554324, 0.47714135, 0.71588457]),
 array([0.68802803, 0.41038376, 0.15602168, 0.99027427, 0.94498102])]

#### 7. Multiply a 5x3 numpy array by a 1x3 numpy array containing random integer values with some fixed seed. 

#### 7. Ստեղծեք 5x3 ու 1x3 չափանի numpy array-ներ որոնք պարունակում են պատահական integer տիպի արժեքներ ֆիքսված seed-ով։ Գտեք առաջին և երկրորդ  array-ների արտադրյալը։ 

In [11]:
np.random.seed(42)
n1 = np.random.rand(5, 3)
n2 = np.random.rand(1, 3)
n1 * n2

array([[0.06869235, 0.28924745, 0.38411853],
       [0.10979667, 0.04746746, 0.08185913],
       [0.0106528 , 0.26352737, 0.31543897],
       [0.1298637 , 0.00626267, 0.50896643],
       [0.15267373, 0.06460253, 0.09541382]])

#### 8. Write a program to sort an array of integers of shape 3x3 first along the columns, the along rows and finally flatten the array so that it becomes an one dimentional array of size 9 and sort the flattened array. 

#### 8. Գրեք ծրագիր որը կսորտավորի ձեր ցանկացած թվերով լցված 3x3 չափանի array-ը սկզբում ըստ սյուների, հետո ըստ տողերի, ապա flatten արեք array-ը դարձնելով այն 9 արժեք պարունակող 1 չափանի array ու սորտավորեք այն։ 

In [13]:
a = np.random.rand(3, 3)
print(a)
print(np.sort(a, axis=0))
print(np.sort(a, axis=1))
print(np.sort(a.flatten()))

[[0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159]
 [0.94888554 0.96563203 0.80839735]]
[[0.51423444 0.17052412 0.04645041]
 [0.60754485 0.59241457 0.06505159]
 [0.94888554 0.96563203 0.80839735]]
[[0.04645041 0.51423444 0.59241457]
 [0.06505159 0.17052412 0.60754485]
 [0.80839735 0.94888554 0.96563203]]
[0.04645041 0.06505159 0.17052412 0.51423444 0.59241457 0.60754485
 0.80839735 0.94888554 0.96563203]


#### 9. Create a 7 x 7 numpy array of zeros and then "frame" it with a border of ones. Your result should look like this:

#### 9. Ստեղծեք 7 x 7 չափանի, 0-ներով լցված numpy array։ Ավելացրեք numpy array-ին 1-երից բաղկացած “շրջանակ”։ Վերջնական արդյունքը պետք է ունենա հետևյալ տեսքը՝

    ![image.png](attachment:image.png)

In [14]:
a = np.zeros((7, 7))
a[[0, 6], :] = 1
a[:, [0, 6]] = 1
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 10. Create the following numpy arrays and calculate the dot product between a and b. Transform the second array if needed.

#### Ստեղծեք հետևյալ numpy array-ները ու հաշվեք a և b array-ների dot product-ը։ Transform արեք երկրորդ array-ը եթե կա դրա կարիքը։

$$a = \begin{bmatrix} 1 & 3 \\ 3 & 13 \\ 0 & -1  \end{bmatrix}$$

$$b = \begin{bmatrix} 1 & 1 \\ 2 & 1 \\ 3 & -3 \end{bmatrix}$$

In [16]:
a = np.array([[1, 3], [3, 13], [0, -1]])
b = np.array([[1, 1], [2, 1], [3, -3]])
a @ b.T

array([[  4,   5,  -6],
       [ 16,  19, -30],
       [ -1,  -1,   3]])